version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  logstash_v5:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Build Gem
          command: gem build logstash-output-datadog_logs.gemspec
      - run:
          name: Install Java
          command: sudo apt-get install openjdk-8-jre
      - run:
          name: Install Logstash
          command: |
            wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
            sudo apt-get install apt-transport-https
            echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list
            sudo apt-get update && sudo apt-get install logstash

  logstash_v6:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Build Gem
          command: gem build logstash-output-datadog_logs.gemspec
      - run:
          name: Install Java
          command: sudo apt-get install openjdk-8-jre
      - run:
          name: Install Logstash
          command: |
            wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
            sudo apt-get install apt-transport-https
            echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list
            sudo apt-get update && sudo apt-get install logstash

  logstash_v7:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Build Gem
          command: gem build logstash-output-datadog_logs.gemspec
      - run:
          name: Install Java
          command: sudo apt-get install openjdk-8-jre
      - run:
          name: Install Logstash
          command: |
            wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
            sudo apt-get install apt-transport-https
            echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
            sudo apt-get update && sudo apt-get install logstash

workflows:
  version: 2.1
  test_logstash:
    jobs:
      - logstash_v5
      - logstash_v6
      - logstash_v7
