version: 2.1
orbs:
  ruby: circleci/ruby@1.0

jobs:
  logstash_v5:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Ruby
          command: sudo apt-get update && sudo apt-get install ruby-full
      - run:
          name: Build Gem
          command: gem build logstash-output-datadog_logs.gemspec
      - run:
          name: Install Java
          command: sudo apt-get update && sudo apt-get install openjdk-8-jre
      - run:
          name: Install Logstash
          command: |
            wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
            sudo apt-get install apt-transport-https
            echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list
            sudo apt-get update && sudo apt-get install logstash
      - run:
          name: Install Plugin
          command: sudo /usr/share/logstash/bin/logstash-plugin install logstash-output-datadog_logs-$(cat lib/logstash/outputs/version.rb| grep VERSION| cut -d"'" -f2).gem
      - run:
          name: Run Logstash
          shell: /bin/sh
          command: |
            sudo timeout 30s /usr/share/logstash/bin/logstash -r -f "test/test.conf"
            test "$?" -eq 124

  logstash_v6:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Ruby
          command: sudo apt-get update && sudo apt-get install ruby-full
      - run:
          name: Build Gem
          command: gem build logstash-output-datadog_logs.gemspec
      - run:
          name: Install Java
          command: sudo apt-get update && sudo apt-get install openjdk-8-jre
      - run:
          name: Install Logstash
          command: |
            wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
            sudo apt-get install apt-transport-https
            echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list
            sudo apt-get update && sudo apt-get install logstash
      - run:
          name: Install Plugin
          command: sudo /usr/share/logstash/bin/logstash-plugin install logstash-output-datadog_logs-$(cat lib/logstash/outputs/version.rb| grep VERSION| cut -d"'" -f2).gem
      - run:
          name: Run Logstash
          shell: /bin/sh
          command: |
            sudo timeout 30s /usr/share/logstash/bin/logstash -r -f "test/test.conf"
            test "$?" -eq 124

  logstash_v7:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Ruby
          command: sudo apt-get update && sudo apt-get install ruby-full
      - run:
          name: Build Gem
          command: gem build logstash-output-datadog_logs.gemspec
      - run:
          name: Install Java
          command: sudo apt-get update && sudo apt-get install openjdk-8-jre
      - run:
          name: Install Logstash
          command: |
            wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
            sudo apt-get install apt-transport-https
            echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
            sudo apt-get update && sudo apt-get install logstash
      - run:
          name: Install Plugin
          command: sudo /usr/share/logstash/bin/logstash-plugin install logstash-output-datadog_logs-$(cat lib/logstash/outputs/version.rb| grep VERSION| cut -d"'" -f2).gem
      - run:
          name: Run Logstash
          shell: /bin/sh
          command: |
            sudo timeout 30s /usr/share/logstash/bin/logstash -r -f "test/test.conf"
            test "$?" -eq 124

  test:
    docker:
      - image: circleci/jruby:9.2.11.1-jre8-node-browsers

    steps:
      - checkout
      - run: gem update --system
      - run: gem install bundler
      - run: bundle install --path vendor/bundle
      - run: bundle exec rspec


workflows:
  version: 2.1
  test_logstash:
    jobs:
      - logstash_v5
      - logstash_v6
      - logstash_v7
      - test
