version: 2.1

jobs:
  build:
    docker:
      - image: alpine:3.7
      - image: docker.elastic.co/logstash/logstash:5.6.16
      - image: docker.elastic.co/logstash/logstash:6.8.10
      - image: docker.elastic.co/logstash/logstash:7.7.1

    steps:
      - run: sleep 5
